<template>
  <div
    class="bg-base-200 overflow-hidden shadow sm:rounded-lg p-6 slide-in-blurred-bottom"
  >
    <h2 class="text-2xl leading-7 font-semibold">Hi there,</h2>
    <div class="mt-3">
      My name is
      <span class="underline decoration-wavy decoration-blue" title="@fajarbc"
        >{{fullName}}</span
      >
      and I'm planning to build something here, just for fun. <br />FYI, this
      page is built with Nuxt 3 (Vue 3) as frontend framework, Tailwind as
      styling, Vite as the build tool and uses Github Action Workflows for the
      deployments.
      <div class="flex items-center gap-1">
        <IconGithub /> Github Repository:
        <a
          href="https://github.com/fajarbc/fajarbc.github.io/"
          class="underline"
          target="_blank"
          title="fajarbc.github.io"
        >
          fajarbc.github.io
        </a>
      </div>
    </div>
    <div class="mt-4 pt-4 border-t border-dashed">
      For now you can try to open:
      <ul v-for="project in projects" :key="project.title">
        <li class="py-2">
          <details :open="project.open_description">
            <summary>
              <a
                :href="`${project.demo ?? '#'}`"
                class="underline ml-4 md:ml-0"
                target="_blank"
                :title="`${
                  project.title ? 'Demo of ' + project.title : 'No Demo'
                }`"
              >
                {{ project.title }}
              </a>
            </summary>
            <div>
              <span v-html="project.description"></span>
              <div class="flex items-center gap-1">
                <IconGithub /> Github Repository:
                <a
                  :href="project.reposiory"
                  class="underline"
                  target="_blank"
                  :title="`${project.reposiory_title} - Github Repository`"
                >
                  {{ project.reposiory_title }}
                </a>
              </div>
            </div>
          </details>
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup>
import IconGithub from "./icons/IconGithub.vue";
import { projects } from "../projects.json";
const fullName = import.meta.env.VITE_FULLNAME;
</script>

<style>
.slide-in-blurred-bottom {
  -webkit-animation: slide-in-blurred-bottom 2s cubic-bezier(0.23, 1, 0.32, 1)
    1s both;
  animation: slide-in-blurred-bottom 2s cubic-bezier(0.23, 1, 0.32, 1) 2s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-9-24 0:48:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slide-in-blurred-bottom {
  0% {
    -webkit-transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
    transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
    -webkit-transform-origin: 1 100%;
    transform-origin: 1 100%;
    -webkit-filter: blur(40px);
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) scaleY(1) scaleX(1);
    transform: translateY(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 1 1;
    transform-origin: 1 1;
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }
}
@keyframes slide-in-blurred-bottom {
  0% {
    -webkit-transform: translateY(1000px) scaleY(2.5) scaleX(0.2);
    transform: translateY(1000px) scaleY(2.5) scaleX(0.2);
    -webkit-transform-origin: 1 100%;
    transform-origin: 1 100%;
    -webkit-filter: blur(40px);
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) scaleY(1) scaleX(1);
    transform: translateY(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 1 1;
    transform-origin: 1 1;
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }
}
</style>
