<template>
  <div class="flex flex-col space-y-2 lg:space-y-4">
    <div class="flex justify-center">
      <img
        src="assets/images/me.jpg"
        :alt="`${fullName} Image`"
        :title="`${fullName} Image`"
        class="rounded-full drop-shadow-2xl sm:drop-shadow-lg image-enter"
        width="200"
      />
    </div>
    <div class="flex justify-center">
      <span class="text-enter">{{ fullName }}</span>
    </div>
    <div class="flex justify-center fadein">
      <IconLocation :title="`Location ${location}`" /> {{ location }}
    </div>
    <div class="flex justify-center space-x-2 fadein">
      <a :href="urlGithub" target="_blank">
        <IconGithub />
      </a>
      <a :href="urlLinkedin" target="_blank">
        <IconLinkedin />
      </a>
    </div>
    <div class="flex justify-center fadein">
      <ThemeOption></ThemeOption>
    </div>
  </div>
</template>

<script setup>
import IconGithub from "./icons/IconGithub.vue";
import IconLinkedin from "./icons/IconLinkedin.vue";
import IconLocation from "./icons/IconLocation.vue";
import ThemeOption from "./ThemeOption.vue";

const fullName = import.meta.env.VITE_FULLNAME;
const location = import.meta.env.VITE_LOCATION;
const urlGithub = import.meta.env.VITE_URL_GITHUB;
const urlLinkedin = import.meta.env.VITE_URL_LINKEDIN;
</script>

<style>
.fadein {
  -webkit-animation: fade-in-fwd 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both
    1s;
  animation: fade-in-fwd 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both 1s;
}

.text-enter {
  -webkit-animation: slide-in-blurred-top 1s cubic-bezier(0.23, 1, 0.32, 1) both;
  animation: slide-in-blurred-top 1s cubic-bezier(0.23, 1, 0.32, 1) both 0.8s;
}
.image-enter {
  -webkit-animation: tilt-in-fwd-tl 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: tilt-in-fwd-tl 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-9-24 1:3:14
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes tilt-in-fwd-tl {
  0% {
    -webkit-transform: rotateY(-20deg) rotateX(35deg) translate(-300px, -300px)
      skew(35deg, -10deg);
    transform: rotateY(-20deg) rotateX(35deg) translate(-300px, -300px)
      skew(35deg, -10deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateY(0) rotateX(0deg) translate(0, 0) skew(0deg, 0deg);
    transform: rotateY(0) rotateX(0deg) translate(0, 0) skew(0deg, 0deg);
    opacity: 1;
  }
}
@keyframes tilt-in-fwd-tl {
  0% {
    -webkit-transform: rotateY(-20deg) rotateX(35deg) translate(-300px, -300px)
      skew(35deg, -10deg);
    transform: rotateY(-20deg) rotateX(35deg) translate(-300px, -300px)
      skew(35deg, -10deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateY(0) rotateX(0deg) translate(0, 0) skew(0deg, 0deg);
    transform: rotateY(0) rotateX(0deg) translate(0, 0) skew(0deg, 0deg);
    opacity: 1;
  }
}
@-webkit-keyframes fade-in-fwd {
  0% {
    -webkit-transform: translateZ(-80px);
    transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes fade-in-fwd {
  0% {
    -webkit-transform: translateZ(-80px);
    transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
@-webkit-keyframes slide-in-blurred-top {
  0% {
    -webkit-transform: translateY(-200px) scaleY(2.5) scaleX(0.2);
    transform: translateY(-200px) scaleY(2.5) scaleX(0.2);
    -webkit-transform-origin: 50% 0;
    transform-origin: 50% 0;
    -webkit-filter: blur(40px);
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) scaleY(1) scaleX(1);
    transform: translateY(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }
}
@keyframes slide-in-blurred-top {
  0% {
    -webkit-transform: translateY(-200px) scaleY(2.5) scaleX(0.2);
    transform: translateY(-200px) scaleY(2.5) scaleX(0.2);
    -webkit-transform-origin: 50% 0;
    transform-origin: 50% 0;
    -webkit-filter: blur(40px);
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) scaleY(1) scaleX(1);
    transform: translateY(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }
}
</style>
